volumes:
    mysql_data:

services:
    nginx:
        container_name: task-nginx
        image: nginx:stable-alpine
        ports:
            - "8000:80"
        volumes:
            - "${PWD}:/var/www:delegated"
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        container_name: task-fpm
        build:
            context: ./docker/images/php-fpm
            dockerfile: Dockerfile
        volumes:
            - "${PWD}:/var/www:delegated"
    database:
        image: percona:8.0
        container_name: task-db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: taskdb
            MYSQL_USER: taskuser
            MYSQL_PASSWORD: taskpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always